source=/nix/store/mbnn5ark4a1lnksxhi3i8fhz9nq8clan-catppuccin-hyprland-0-unstable-2024-06-19/mocha.conf
source=/nix/store/sqy0ia1lhgdwsdr8rprisqca2iwv8pd0-hyprland-mauve-accent.conf
source=/nix/store/h6g9lzxkbs1ww7hpymr8y0s1sda6hlkf-catppuccin-hyprlock-0
background {
  blur_passes=2
  blur_size=4
  color=rgb(1e1e2e)
}

general {
  hide_cursor=true
}

input-field {
  size=300, 50
  check_color=rgb(cba6f7)
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.350000
  fade_on_empty=false
  fail_color=rgb(f38ba8)
  font_color=rgb(cdd6f4)
  halign=center
  hide_input=false
  inner_color=rgb(1e1e2e)
  outer_color=rgb(313244)
  outline_thickness=2
  placeholder_text=
  position=0, -50
  valign=center
}

label {
  color=rgb(cdd6f4)
  font_family=JetBrains Mono NF
  font_size=96
  halign=center
  position=0, 200
  shadow_color=rgb(11111b)
  shadow_passes=1
  text=$TIME
  valign=center
}

label {
  color=rgb(a6adc8)
  font_family=JetBrains Mono NF
  font_size=24
  halign=center
  position=0, 100
  text=cmd[update:1000] date +"%A, %d %B"
  valign=center
}
